### ISSUE TITLE
org-agenda for items that are not scheduled

### ISSUE THREAD

**Issue by pmiddend** [alphapapa/org-super-agenda#129]
I was a little confused by reading org-super-agenda's readme. So this is either a README issue or just a question. Sorry for being vague.

What I wanted to have is an agenda for `TODO` items that are due/overdue (just like the normal `org-agenda`) and along that, a list of items that have _no_ schedule date or deadline. This way, I can see what I _have_ to do today (e.g. pay bills) and what I _can_ do today (e.g. read book X, watch show Y, ...).

The only way I've managed to display items that are not scheduled, however, is to use `M-x org-todo-list` instead of `M-x org-agenda`. In the todo view, I'm losing functionality though. I cannot shift the schedule date, for example.

Should this be made clear in the README, maybe?

**Comment by alphapapa** [comment]
This is a common misunderstanding among users.  I get probably one or two questions like this a month.  The issue, I think, is not so much this package, but that users tend to be confused by Org Agenda.  It's a complicated beast, and it tends to obscure the way that entries are selected for display.  

This package only *groups* items.  It does not *find* or *select* them.  The description in the readme does explain the package's purpose:

> So this package **filters the results** from org-agenda-finalize-entries, which runs just before items are inserted into agenda views. It **runs them through a set of filters that separate them into groups.** Then the groups are inserted into the agenda buffer, and any remaining items are inserted at the end. Empty groups are not displayed.

> **The end result is your standard daily/weekly agenda, but arranged into groups defined by you.** You might put items with certain tags in one group, habits in another group, items with certain todo keywords in another, and items with certain priorities in another. The possibilities are only limited by the grouping functions.

> The **primary use of this package is for the daily/weekly agenda, made by the org-agenda-list command, but it also works for other agenda views, like org-tags-view, org-todo-list, org-search-view, etc.**

Documentation can always be improved, of course, so if you have specific suggestions, feel free to make them.  But I think the problem here is that users tend to not read documentation very thoroughly in the first place, and they tend to not understand how the Agenda works, so when they see the filter language in this package, they tend to misunderstand what it does.

In your case, you're using the daily/weekly agenda which, by its nature, only shows items based on timestamps.  You have basically two choices:

1.  Use a custom agenda command with multiple blocks.
2.  Use `org-ql` instead of the agenda.

This kind of confusion is why I wrote org-ql.  It doesn't obscure the queries and it makes them easy to write.  It does not replicate all features of Org Agenda, but for your needs, it will probably suffice, and will likely perform better as well.

**Comment by alphapapa** [comment]
I added a FAQ here: https://github.com/alphapapa/org-super-agenda#faq  Please let me know what you think.  The problem, of course, is getting users to read it.  ;)

**Comment by pmiddend** [comment]
Excellent answer @alphapapa. I really did read the documentation and you explain it very well. On my part, it was just me not understanding Org Agenda well enough. I'd have thought it can handle plain headlines without a schedule date, but I was wrong.
I'll take a look at org-ql now. Thanks for a great set of packages!

**Comment by alphapapa** [comment]
Apologies if I sounded like I was accusing you of not reading carefully.  Obviously you do, but a lot of users don't.  :)  Thanks for your feedback.
