### ISSUE TITLE
Document non-guaranteed item order

### ISSUE THREAD

**Issue by garrison** [alphapapa/org-super-agenda#155]
I would like there to be an `:or` selector that implements the union operation, like `:and` which implements intersection.  Yes, a union is really the default if multiple selectors are specified; but the original order of items is not preserved in this case: it's everything that matches the first, followed by everything that matches the second, and so on.  I would like to match multiple selectors without messing up the order that is returned by the original agenda (in particular, this is for my habits, which I want to be displayed most overdue first, as is the default in orgmode).  But first I wanted to ask: is there a way to do this already?

**Comment by garrison** [comment]
For now I have solved this by adding an extra selector above my existing ones.  Before, I matched scheduled for today items right before my habits, and I always wondered why some habits were shown at the top of my habits list, despite being completed recently.  It turns out that these were actually matching the first selector, which targeted items scheduled today.  Still, I think having `:or` would be useful, as it would give me even more flexibility in ordering things.

**Comment by alphapapa** [comment]
Because hash tables are used in some parts of the implementation, ordering may not be preserved.  An explicit `:or` selector like you suggest might help mitigate that in some cases, but I don't think it would guarantee it.

I would be reluctant to add an `:or` selector because, from the user's perspective, it would duplicate functionality and could be confusing.  I can imagine the questions I would receive here asking what the difference is or which should be used.

In the long run, this package's functionality should probably be reimplemented using lambdas and sexps, similar to the code in `org-ql` and `bufler`, which would probably make the grouping DSL more consistent.  I've learned a lot since I wrote `org-super-agenda`.  Although it's possible that, in Elisp, the current implementation might be faster than one using lambdas would be, so it would need benchmarking.

For those reasons, I'm not very interested in implementing an `:or` selector myself.  I'd be willing to consider a well-written patch, but I can't promise I'd merge one.  :)

What do you think?  Thanks.

**Comment by garrison** [comment]
Thanks for the response.  Yeah, the `:or` selector is not really helpful without an ordering guarantee.  It sounds like the better path forward is to investigate the one you proposed.

**Comment by alphapapa** [comment]
Ok.  In that case, I'll repurpose this issue to note that I should document the ordering issue.  Thanks.
