### ISSUE TITLE
DONE items not showing under the desired "Done today" group

### ISSUE THREAD

**Issue by iburunat** [alphapapa/org-super-agenda#156]
First off, congrats for this excellent, most useful tool. It has made my emacs flow so much smoother. 

With `log mode` enabled, I am trying to show `DONE` items in a specific heading in `org-super-agenda`. I have tried this setup below:

```
 (setq org-super-agenda-groups
       '(  
          (:name "Today"
                  :time-grid t)
          (:name "Deadlines"
                  :deadline today
                  :order 0)
          (:name "Research"
                  :category "research")
          (:name "Personal tasks"
                  :scheduled today 
                  :order 4)
          (:name "Done today"
                  :todo "DONE")
           ))
```

However, the `DONE` items appearing under "`Done today`" are those that are repeated tasks. Otherwise, `DONE` items are shown below "`other items`". Would the solution be to use the `:discard` or `:not` selectors in each group to exclude `DONE` from them?

Thanks in advance!

**Comment by alphapapa** [comment]
Thanks for the kind words.  I'm glad it's useful to you.

I don't understand the problem you are describing, because you haven't provided enough information.  However, I'm guessing the issue may be one described in the FAQ: https://github.com/alphapapa/org-super-agenda#faq

**Comment by iburunat** [comment]
Thanks for the prompt response. The DONE tasks appear on my agenda when not using org-super-agenda (because I have `log-mode `enabled). They also do appear using the `org-super-agenda`, but not under the `"Done Today"` group I created (instead they appear on the "Today" group, which I now realize I skipped in my original description of the problem! (see updated above).

**Comment by alphapapa** [comment]
Okay, you didn't mention log mode.  Log mode entries are different than regular ones.  IIRC they are collected by the `:time-grid` selector.  So what you're seeing are not DONE tasks but log entries.  They are different things in Org Agenda terms.

**Comment by iburunat** [comment]
Thanks, I see. So the question remains. How to make the `DONE` tasks show not a logged but as status items such as `TODO`?

**Comment by alphapapa** [comment]
Assuming that I'm understanding you correctly, there seems to be some misunderstanding about how Org Agenda works and what `org-super-agenda` does.  Please refer to the FAQ entry again.  Your question is not about `org-super-agenda` but about Org Agenda.  For information about that, please refer to the Org manual, community documentation and resources, etc.

**Comment by nchachereau** [comment]
@iburunat in my own configuration, I have something similar to what you are trying to do. If I take your own code, it could something like this (I have not tried this specific setup though…):

```elisp
 (setq org-super-agenda-groups
       '((:name "Done today"
                  :todo "DONE"
                  :log closed
                  :order 4))
         (:name "Today"
                  :time-grid t)
         (:name "Deadlines"
                  :deadline today
                  :order 0)
         (:name "Research"
                  :category "research")
         (:name "Personal tasks"
                  :scheduled today)))

```

To explain a bit more: org-mode prepares all entries that will be shown by the agenda. org-super-agenda then filters and groups them. In that case, all tasks for the agenda view, here among others deadlines and scheduled for the day shown + log entries since you have configured to show log entries, will be passed to org-super-agenda. We can then select all entries that have been logged on that day (as @alphapapa has said, log entries are different from the other entries) by using the `:log` selector. `:log closed` only selects entries that have been "closed" (say, marked as done). `:todo "DONE"` selects all entries that are not log entries but that have been marked as DONE. Since most of these entries probably match one of your other groups (shown on today's timegrid, have deadlines, scheduled to today, coming from the "research" category), I have created the group before the others but changed its display position with `:order 4`.

You will notice that items that have been scheduled for today and marked as DONE will be shown twice, once as normal entries, and once as log entries. If you prefer to avoid this, you might use something like (I have this in my own config): `(:discard (:and (:scheduled t :todo "DONE" :not (:log closed))))`, i.e. discarding any entry that was scheduled, has been marked as DONE but is not a log entry. This would give something like:

```elisp
 (setq org-super-agenda-groups
       '((:discard (:and (:scheduled t
                            :todo "DONE"
                            :not (:log closed))))
         (:name "Done today"
                  :log closed
                  :order 4))
         (:name "Today"
                  :time-grid t)
         (:name "Deadlines"
                  :deadline today
                  :order 0)
         (:name "Research"
                  :category "research"
         (:name "Personal tasks"
                  :scheduled today)))
```

This might be incomplete (I have not tested what I have written here and my own setup is rather more complicated; BTW you might want to look into custom agenda views, they are cool), but I hope it will help you achieve what you want. You will probably need to experiment, but I am sure you will find a solution!

**Comment by iburunat** [comment]
First off, thanks a bunch, @nchachereau for the lengthy response! It's by virtue of altruistic users like you that makes Github so special. Now I think I got the logic behind the package. I used your clear examples, and they (after removing an extra parenthesis :o) work. My agenda looks so organized and perfect now. I am eternally indebted :)
