### ISSUE TITLE
Question: Sorting groups with :auto selectors

### ISSUE THREAD

**Issue by djelenc** [alphapapa/org-super-agenda#159]
I wonder whether is it possible to determine the order in which groups are displayed if a `:auto-` selector is used. I am using the `:auto-map` to collect all tasks under their top-level heading. I enclose my code snippet below.

```elisp
(:auto-map (lambda (item)
      ;; name each project by its top-level heading
      (re-search-backward "^\* " nil t)
      (org-get-heading t t t t))
:order 3)
```
(This is very similar to how `:auto-parent` works, except that it does not consider nested hierarchies to be separate projects.) While this works exactly how I want, I would like sometimes to shuffle the order in which groups are displayed. By default the sorting is done alphabetically. Is it possible to sort such groups by a custom property or by a priority?

Thank you for your response and for making this nice piece of software.

**Comment by alphapapa** [comment]
> Thank you for your response and for making this nice piece of software.

Thank you for the kind words.

For your question, please search the issue tracker for "sorting".

**Comment by djelenc** [comment]
For posterity sake: [no, this is currently not possible.](https://github.com/alphapapa/org-super-agenda/issues/106#issuecomment-529546055)

**Comment by EFLS** [comment]
I was looking for something similar: influence sorting of `:auto-parent`. My solution was to make sure every relevant parent headline has a priority, as these are included in the name & sorting process. `[#A]` will be sorted before `[#B]`.

One challenge is that headings without priority will be sorted before `[#A]`, which is why this only works to satisfaction if each parent headline has a priority.
