### ISSUE TITLE
Stronger visual separation between week days

### ISSUE THREAD

**Issue by floli** [alphapapa/org-super-agenda#161]
I have set up my org-super-agenda like that:
```
(setq org-super-agenda-groups '(
                                          (:name "Agenda"                
                                                 :time-grid)
                                          (:name "Tasks"                
                                                 :auto-outline-path t
                                                 :order -1)))
```
With that, I have all timed items under `Agenda` and items that only have a date above.

How can I achieve a stronger visual separation between days, e.g. a bigger font or another face (color) for the weekdays font?

Thanks!

**Comment by alphapapa** [comment]
I don't understand quite what you are asking.  However, I'm guessing that what you want is covered by existing functionality, which should be described in the readme and in `M-x customize-group RET org-super-agenda RET`.  If it is not, please post your question on, e.g. old.reddit.com/r/orgmode so that other users can assist and benefit from answers.
