### ISSUE TITLE
Is it possible to set :name dynamically?

### ISSUE THREAD

**Issue by OlMon** [alphapapa/org-super-agenda#186]
Hej Hej,

First: Thank you very much for all your contributions!

Maybe it is my low level knowledge of lisp, but I can not set the :name property dynamically.
Small example what I am trying to do:
`(:name (concat "test" " working"))`
I tried to set it to a variable but that does not work either....
`(setq myVar (concat "test" " working")) [...] (:name myVar) [...]`

The error I get is: "org-super-agenda--make-agenda-header: Wrong type argument: buffer-or-string-p"

Is this not possible or am I to green at lisp at the moment?

Cheers and Thank you,
OlMon

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.

Yes, the issue seems to be that you need to study some basic Lisp, specifically how lists, quoting, backquoting, and splicing work.  These should be covered by the Emacs Lisp Introduction (`eintr` in the Emacs Info manuals) and the Elisp manual (the `elisp` manual).  

As well, this topic (and this specific question) come up not infrequently on Reddit's r/emacs and r/orgmode.  If you have more questions like this, please ask them there so that other people can offer and receive help rather than only you and me.
