### ISSUE TITLE
org-agenda-current-subtree-or-region--is this related to org-super-agenda?

### ISSUE THREAD

**Issue by rieje** [alphapapa/org-super-agenda#35]
Hey alphapapa, really sorry for probably irrelevant topic, but I came across a function called `org-agenda-current-subtree-or-region` that you shared in this [post](https://mollermara.com/blog/Fast-refiling-in-org-mode-with-hydras/) regarding efficient refiling in org-mode using hydras.

Could you tell me when this would be useful?  When I'm in org-agenda, I can `C-c C-w` to refile, but isn't that just normal refiling? How does making an agenda view of a current subtree or region make refiling more efficient? What do you use `org-agenda-current-subtree-or-region` for (and have you fixed any of the mentioned bugs or are you still using the exact same function?)?

As you can tell, I'm pretty new to `org-agenda`. I'm just trying to understand how it can be useful, maybe you have an example.

Also, normal `org-agenda` sorts stuff in the following manner: specific deadlines/schedules on top, then any results in the order of the files in `org-agenda-files` variable, right? And `org-super-agenda` aims to filter and group similar (defined by the user) items together and can also sort how it's displayed in `org-agenda`? What are good reasons *not* to use `org-super-agenda`, since it seems more useful than vanilla `org-agenda`?

Much appreciated.

**Comment by alphapapa** [comment]
>  When I'm in org-agenda, I can C-c C-w to refile, but isn't that just normal refiling? How does making an agenda view of a current subtree or region make refiling more efficient?

It doesn't necessarily, but it might be helpful if you want to refile several items to different places quickly, as it saves you from navigating all the non-headline content in the Org buffer.  Whatever works best at the time.

`org-agenda-current-subtree-or-region` is useful for simply viewing a subtree or region in an agenda view.  For example, if you have a project in a subtree, you might want to see only that subtree in an agenda view.  You could use the agenda dispatcher to set the restriction and then open the agenda, or you could use this function to do it for you, bound to a single key.  Then you can do anything you can do in an agenda view with those items.

> and have you fixed any of the mentioned bugs or are you still using the exact same function?

I don't recall making any changes since then, but if you are finding those bugs a problem, let me know and maybe I can fix them.

> What are good reasons not to use org-super-agenda, since it seems more useful than vanilla org-agenda?

Um...well, if you want to view items without grouping them...other than that, use it whenever you find it useful.  There's little-to-no performance penalty and no harmful side effects.
