### ISSUE TITLE
Hide empty group after setting org-agenda-filter-by-*

### ISSUE THREAD

**Issue by cslux** [alphapapa/org-super-agenda#56]
Is this possible?

**Comment by cslux** [comment]
When I'm inside the org-agenda buffer and call one of the `org-agenda-filter-by-*`, than it's possible that no, tasks are left for that group. I expect that group to be hidden as well.


![screenshot from 2018-11-15 07-46-46](https://user-images.githubusercontent.com/1712313/48535192-bbf0b980-e8aa-11e8-870a-718d7289f5e0.png)

**Comment by alphapapa** [comment]
I actually wasn't aware of those functions.

I think it would be possible to support that, but you'd have to add a function that runs after the filter function that would hide headers without items, using the same method as the filter function.

Since I don't use this feature myself, I may not add it myself.  Patches welcome.  :)

**Comment by cslux** [comment]
I'll look into that.

**Comment by alphapapa** [comment]
You might be able to accomplish it with advice (i.e. `advice-add`).

**Comment by ngharrison** [comment]
@cslux I still get empty groups after executing `(setq org-super-agenda-hide-empty-groups t)`. Was there something else required to enable this feature?

Example:
1. Run `org-todo-list`
2. Run `org-agenda-filter-by-tag`, choosing a tag
3. I get some headers with no items as shown in your original image

**Comment by cslux** [comment]
Hey! Indeed, it doesn't work anymore. Something must have changed in the org. I'll
look into it in the next couple of days.

**Comment by alphapapa** [comment]
Please file a new issue for this new problem.
