### ISSUE TITLE
Request: :date with 'future' option

### ISSUE THREAD

**Issue by DSMasterson** [alphapapa/org-super-agenda#85]
I'm learning to mark meetings with a :todo of "MEETING" and a specific :date for when the meeting will be.  These meetings, at the moment, are anything that might have a date/time attached to it (work meeting, school meeting, place to go at a particular time).  I'd like to have an agenda that includes a list of my meetings in the future (preferably sorted by date).  I guess my first need is a "future" option to the ";date" selector.  Meetings don't really agree with DEADLINES, so setting this up with deadlines doesn't really seem right.

Make sense?

**Comment by DSMasterson** [comment]
Hmm.  Thinking about this further.  If I mark "MEETING" as "DONE", then all "MEETING"s will be either today (and picked up in :time-grid) or in the future (and picked up in :todo), so there really is no need for this future date.  I guess, though, I'll have to post tag meetings if I want to report on meetings I attended at a later time.  Hmm.

Suggestions..?

**Comment by alphapapa** [comment]
Many people (including myself) tend to, at times, find the Org format confusing with regard to time/date metadata.  They wonder whether they should use SCHEDULED, DEADLINE, or an active timestamp in the heading or body.  The Org manual gives some guidance on it, but that model doesn't fit everyone's mental model, so many users adopt their own solutions.  Nevertheless, Org is designed around that one model, so the software tends to follow it (at least, software designed for general use).

In this case, for--I will call them--appointments, the "Org way" is to use active timestamps in an entry--not DEADLINE or SCHEDULED.

You may already be aware of all that; I'm just trying to establish common ground.

The `:date` selector in this package uses the `ts-date` text property created by the Org Agenda code.  I haven't looked at that code in a long time, so I don't recall which kinds of time/date metadata ends up in that property, i.e. is it any active timestamp in an entry, or only in the heading, or is it DEADLINE/SCHEDULED lines, or what if there are multiple ones, which is selected?  etc.  As you can see, it's not as straightforward as it might seem.

Keep in mind that org-super-agenda is more intended for organizing and presenting the results gathered by Org Agenda, rather than doing the gathering itself.  So, in general, your query is best handled by the Org Agenda code, not by org-super-agenda, i.e. you should be selecting entries with an Org Agenda search.  That will also be much faster than, e.g. selecting many results that are undesired and filtering them out with org-super-agenda.

In `org-ql`, I recently added a selector that checks all dates and ranges in entries: https://github.com/alphapapa/org-ql/commit/c5599a6030eb6f0b8e7a181cbbeb7c323a037d63  While it won't generally be as fast as a custom Org Agenda search, the syntax is more lispy and easier for me to remember.  You could do a simple search like:
```el
(org-ql-agenda "calendar.org"
  (date >= today))
```

I hope this is helpful.  If it doesn't answer your question, feel free to ask again, perhaps a bit more specifically.  ;)

**Comment by DSMasterson** [comment]
That makes sense and I think I just figured out a way to do this with ELisp and org-super-agenda.  Thanks.
