### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by rjhorn-agfa** [alphapapa/org-super-agenda#9]
I just finished getting org-super-agenda installed, and there are some issues that could be better documented.  Only one affects the code directly.

Calling this a "mode" is confusing.  All the other "modes", like "lisp-mode" and "org-mode", are buffer modes that affect buffer behavior.   Calling the variable  "org-super-agenda-active" rather than  "org-super-agenda-mode" would be less confusing.  I was also initially looking for something on the mode-line, which would only be appropriate if this were a buffer mode.

The other problem results from with my issues with MELPA.  I have a personal git area where I modify parts of org-mode and other packages.  MELPA corrupts my org-mode when it installs it as a dependency.  I have not dug through MELPA lisp code to figure how to stop this.  Org-super-agenda lists org as a dependency, so MELPA corrupted it.

A discussion of dependencies and how to install without MELPA would help.  Reading the lisp code and figuring out the dependencies was not too hard, but it was time consuming.  I also had to undo the corruption of org-mode inflicted by MELPA.

**Comment by alphapapa** [comment]
Hi,

> Calling this a "mode" is confusing. All the other "modes", like "lisp-mode" and "org-mode", are buffer modes that affect buffer behavior. Calling the variable "org-super-agenda-active" rather than "org-super-agenda-mode" would be less confusing. I was also initially looking for something on the mode-line, which would only be appropriate if this were a buffer mode.

Well, it's a global minor mode, so the convention is for the variable to end in `-mode`.  And as you said, since it's not a buffer mode, there's no need for a lighter.  I think this is the standard way to do this in Emacs.

> The other problem results from with my issues with MELPA. I have a personal git area where I modify parts of org-mode and other packages. MELPA corrupts my org-mode when it installs it as a dependency. I have not dug through MELPA lisp code to figure how to stop this. Org-super-agenda lists org as a dependency, so MELPA corrupted it.

I also keep `elpa/` in git, but I don't have any corruption issues like you describe.  The only reason installing this package would have installed Org is if you didn't already have Org installed at the version required.

I'm not sure exactly what kind of changes you're making to packages, but you should be able to revert any changes made by installing dependencies by using git.  e.g. in Magit you can just open the status buffer and press `k` on any changes you don't want, and they will be reverted to the HEAD commit.

And I don't think "corrupting" is what's happening, because that's not how `package.el` works.  It just installs a new version in a new directory, like mine is `/home/me/.emacs.d/elpa/org-plus-contrib-20170210`.  If I upgrade Org, it will be in a new directory like `/home/me/.emacs.d/elpa/org-plus-contrib-20170814`, and the old directory will remain untouched.  So if you simply delete the newest Org directory, that will cause Emacs to load the old one next time.

I'm afraid there's not much I can do for you if you're modifying packages directly in the `elpa/` directory.  Generally there should not be any need to make changes that way, because you can do nearly anything with custom functions, keymaps, hooks, and function advice.  That's even how this package works, by wrapping an Org function and filtering its output.

If you insist on making changes directly to installed packages, you probably need to use an alternative package manager, like maybe `borg`, which is designed to help users make changes to packages directly.

> A discussion of dependencies and how to install without MELPA would help. Reading the lisp code and figuring out the dependencies was not too hard, but it was time consuming.

Good point, I'll add a list of dependencies to the readme.

Thanks for your feedback.

**Comment by rjhorn-agfa** [comment]
I missed that it was a global minor mode.  So the name is appropriate.

I don't put my version of org-mode into the elpa directory.  MELPA did, and the result acted like a mixed installation of org.  The fix was to simply delete the elpa directory.  There is probably some way to tell elpa that I'm providing org and it should accept that the dependency has been met.  I haven't noticed it.
